# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Use Trusty to get a reasonably recent version of Boost.
sudo: required
dist: trusty

language: c++

addons:
    apt:
        packages:
            - libboost-tools-dev
            - libxml2-utils
            - g++-multilib

matrix:
    include:
      - compiler: gcc
        env: |
            label="gcc C++03/11";
            user_config="using gcc : : g++-4.8 --coverage -fsanitize=address -Werror ;"
            enable_coverage=1
            CXXSTD=03,11
      - compiler: gcc
        env: |
            label="gcc 32 bit C++11";
            user_config="using gcc : : g++-4.8 -m32 -fsanitize=address -Werror ;"
            CXXSTD=11
      - compiler: clang
        env: |
            label="clang C++11/17";
            user_config="using clang : : clang++ -fsanitize=address -Werror ;"
            CXXSTD=11,17
        # sanitized=address not available for 32-bit clang on travis.
      - compiler: clang
        env: |
            label="clang 32 bit";
            user_config="using clang : : clang++ -m32 -Werror --std=c++03 ;"

before_install:
    - if [ -n $enable_coverage ]; then pip install --user cpp-coveralls; fi

before_script:
    - export BOOST_VERSION=1.66.0
    - export BOOST_FILENAME=boost_1_66_0
    - export BOOST_ROOT=${HOME}/boost
    - cd ${TRAVIS_BUILD_DIR}
    - touch Jamroot.jam
    - cd $HOME
    - echo $user_config > ~/user-config.jam
    - cat ~/user-config.jam
    - |
        # Pick snapshot to use
        if [ "$TRAVIS_EVENT_TYPE" == "cron" ]
        then
            if [ "$TRAVIS_BRANCH" == "master" ]
            then
                snapshot=master
            else
                snapshot=develop
            fi
        else
            snapshot=stable
        fi

        # Set download_url for snapshot
        if [ $snapshot == "stable" ]
        then
            download_url=https://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/${BOOST_FILENAME}.tar.bz2/download
        else
            download_url=$(curl https://api.bintray.com/packages/boostorg/$snapshot/snapshot/files |
                    python -c "import os.path, sys, json; x = json.load(sys.stdin); print '\n'.join(a['path'] for a in x if os.path.splitext(a['path'])[1] == '.bz2')" |
                    head -n 1 |
                    sed "s/^/http:\/\/dl.bintray.com\/boostorg\/$snapshot\//")
        fi

        # Download and extract snapshot
        echo "Downloading ${download_url}"
        mkdir $HOME/download
        mkdir $HOME/extract
        cd $HOME/download
        wget -O boost.tar.bz2 $download_url
        cd $HOME/extract
        tar -xjf $HOME/download/boost.tar.bz2
        mv * ${BOOST_ROOT}
    - rm -r ${BOOST_ROOT}/boost/unordered

after_success:
    if [ -n $enable_coverage ]; then coveralls -r ${TRAVIS_BUILD_DIR} -b ${TRAVIS_BUILD_DIR}/test --gcov-options '\-lp' --include include/boost/unordered/ ; fi

script:
    - cd ${TRAVIS_BUILD_DIR}/test
    - bjam cxxstd=$CXXSTD -q include=${BOOST_ROOT} include=${TRAVIS_BUILD_DIR}/include
    - xmllint --noout ${TRAVIS_BUILD_DIR}/doc/ref.xml
