# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Use Trusty to get a reasonably recent version of Boost.
sudo: required
dist: trusty

language: c++

addons:
    apt:
        packages:
            - libboost-dev
            - libboost-tools-dev

matrix:
    include:
      - compiler: gcc
        env: BJAM_TOOLSET=gcc
      - compiler: gcc
        env: BJAM_TOOLSET=gcc-std11
      - compiler: clang
        env: BJAM_TOOLSET=clang
      - compiler: clang
        env: BJAM_TOOLSET=clang-std11

before_script:
    - |
        echo "using gcc : : g++-4.8 --std=c++03 -fsanitize=address ;" > ~/user-config.jam
        echo "using gcc : std11 : g++-4.8 --std=c++11 -fsanitize=address ;" >> ~/user-config.jam
        echo "using clang : : clang++ --std=c++03 -fsanitize=address ;" >> ~/user-config.jam
        echo "using clang : std11 : clang++ --std=c++11 -fsanitize=address ;" >> ~/user-config.jam
    - cat ~/user-config.jam
    - touch Jamroot.jam

script:
    - cd test && bjam ${BJAM_TOOLSET} include=${TRAVIS_BUILD_DIR}/include
